# Generated by Django 4.0.6 on 2022-08-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoty', models.CharField(choices=[('Education', 'Education'), ('programing', 'programing'), ('Others', 'Others')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'content_table',
            },
        ),
    ]
